name: Release

on:
  push:
    branches:
      - fork-release

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: true

jobs:
  release:
    name: Changelog PR or Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: pnpm install
      - name: Build Packages
        run: pnpm run build
      - name: Publish to NPM
        run: cd packages/astro && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
